### ISSUE TITLE
Dhrystones come on! Phoronix, LuxMark https://youtu.be/wl5H5rT87JE

### ISSUE THREAD

**Issue by juanpc2018** [geerlingguy/top500-benchmark#11]
http://www.roylongbottom.org.uk/
http://www.roylongbottom.org.uk/dhrystone%20results.htm
Source:
https://netlib.org/benchmark/dhry-c
https://netlib.org/benchmark/

Dhrystones are Fun, but same as Geekbench, all over the place....
Amiga 1200 + PiStom32 + Pi4B does 1.5Million 
https://youtu.be/NDuVh-zOwdc?t=301

much more stable Wine+Cinebench R15 R20 R23
or 
http://wiki.luxcorerender.org/LuxMark#Binaries
x86_64 Requires Intel & AMD CPU OpenCL drivers, for all OS.

https://www.phoronix.com/review/power9-talos-2/2
https://www.phoronix-test-suite.com/

https://youtu.be/wl5H5rT87JE

**Comment by geerlingguy** [comment]
I'm not quite sure what you're suggesting here?

I usually perform a large suite of different benchmarks on SBCs, desktop PCs, and servers, but enjoy running HPL on them as well since that's the penultimate 'cluster benchmark' to measure performance in FLOPs for historical / fun comparison.

Not to mention, GPUs nowadays obliterate CPUs when it comes to this... but that's besides the point :)

See, for example: https://github.com/geerlingguy/sbc-reviews/issues/5
